# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SafelySent' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SafelySent
  pod 'FirebaseUI/Auth'
  pod 'Firebase/Analytics'

  pod 'FirebaseUI/Google'
  pod 'FirebaseUI'
  
  target 'SafelySentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SafelySentUITests' do
    # Pods for testing
  end

end
